### ISSUE TITLE
一个小小的奇怪的疑问：这一行什么用意?

### ISSUE THREAD

**Issue by JanYork** [apache/rocketmq-dashboard#132]
Dockerfile中看到一句：RUN sh -c 'touch /rocketmq-dashboard.jar'
原文：
【
FROM java:8
VOLUME /tmp
ADD rocketmq-dashboard-*.jar rocketmq-dashboard.jar
RUN sh -c 'touch /rocketmq-dashboard.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -jar /rocketmq-dashboard.jar" ]
】

为什么需要创建一个空的jar？

**Comment by iamgd67** [comment]
touch 在文件不存在时是创建空文件，，存在时是改变创建和访问时间
