### ISSUE TITLE
Throwables.propagate is deprecated

### ISSUE THREAD

**Issue by Abhijeetmishr** [apache/rocketmq-dashboard#148]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:
 Throwables.propagate is deprecated
![image](https://user-images.githubusercontent.com/43075376/224615122-da59c369-7622-4fa6-91a8-00cc098c05b3.png)

2. Please tell us about your environment: Windows, VsCode

**Comment by Abhijeetmishr** [comment]
can I raise PR for this  ?

**Comment by Abhijeetmishr** [comment]
@Oliverwqcwrw I am able to open rocketmq-dashboard in local but this issue is popping up ?
![image](https://user-images.githubusercontent.com/43075376/226323132-a371c6b6-7bdd-471c-a909-1f5df65a7ca0.png)

Regards

**Comment by Oliverwqcwrw** [comment]
It looked like the connection to the NameServer failed, please check your cluster if it is working.
