### ISSUE TITLE
使用主从模式的集群创建topic报错

### ISSUE THREAD

**Issue by Liguanqin** [apache/rocketmq-dashboard#166]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
使用主从模式的集群去创建topic

- What did you expect to see?
`Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1 DESC: Can't modify topic or subscription group from slave broker, please execute it from master broker.`

- What did you see instead?

2. Please tell us about your environment:
rocketmq： 5.1.1
rocketmq dashboard：master

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
![image](https://github.com/apache/rocketmq-dashboard/assets/12002367/110ae8b5-8cd7-4229-b3fa-b3c85329a412)
![image](https://github.com/apache/rocketmq-dashboard/assets/12002367/5e5182ed-4b91-45cf-9a6d-db4959ccd177)

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.
既然创建和修改topic都必须要在master节点上操作，那dashboard应该和旧版的console一样，窗口应该只展示master节点，不需要展示slave节点。
2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by chenl0517** [comment]
这并不是bug,而是你的集群配置错误，master和salve是通过brokername来配对的，按照你的集群配置，brokername应该只有broker-a、broker-b、broker-c ，master和salve 都是，而不应该出现a-s,b-s,c-s
