### ISSUE TITLE
请教，怎么两年都没发release了。。。？

### ISSUE THREAD

**Issue by gzlboy** [apache/rocketmq-dashboard#176]
看上去有维护呀，docker hub上面还是2两年前的版本。。。
rocketmq都已经到5.1.3版本了，是不是有些新特性rocketmq-dashboard还不支持？

**Comment by mmzhi** [comment]
背后是阿里团队，员工换了一批又一批，做这些开源的没有业绩，无法盈利，本身国内就卷，不更新是正常

**Comment by iamgd67** [comment]
哎，有pr也不merge，难受

**Comment by mcxinyu** [comment]
不是捐给 Apache 了么？

> 背后是阿里团队，员工换了一批又一批，做这些开源的没有业绩，无法盈利，本身国内就卷，不更新是正常

**Comment by lizhanhui** [comment]
> 哎，有pr也不merge，难受

抱歉带来不好的体验，社区里面确实缺少专注这个repo的committer。 我最近试着维护下，也欢迎熟悉springboot, 前端功能的同学一起参与。

**Comment by mmzhi** [comment]
> 不是捐给 Apache 了么？
> 
> > 背后是阿里团队，员工换了一批又一批，做这些开源的没有业绩，无法盈利，本身国内就卷，不更新是正常

捐给 Apache，Apache只负责管理，又不会主动维护项目
