### ISSUE TITLE
Message track query enhancement

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq-dashboard#19]
Currently, system topic (RMQ_SYS_TRACE_TOPIC) or message track defined in configuration files are used by default for message track query on the console. But now, users can specify specific topic to save message track information when sending and receiving messages on the client. If so, The console cannot query this message track information.

![image](https://user-images.githubusercontent.com/18254437/132642454-76330fdf-64eb-42be-a518-6c5380bd980e.png)

Can we select the previously specified message track topic before the user queries the message track information, like this? @StyleTang @vongosling 

![image](https://user-images.githubusercontent.com/18254437/132642236-7cc34bb2-5d23-4b3c-a176-9486835ea02e.png)

**Comment by StyleTang** [comment]
I think choosing a track message topic manually is not a good user experience. 
Users rarely modify msgTrackTopic, we have a rocketmq.config.msgTrackTopicName config to use a specific message track topic.

**Comment by zhangjidi2016** [comment]
Yes, msgTrackTopic rarely set, but if different users on the client side using different msgTrackTopic In the same cluster, and rocketmq. config. msgTrackTopicName in rocketmq-dashboard can be set only one. I think we should consider this situation.

**Comment by StyleTang** [comment]
I get it, you are right, It is necessary to let users choose the msgTrackTopic by themselves.
