### ISSUE TITLE
Rocketmq5.3.0版本，查看消息详情报错

### ISSUE THREAD

**Issue by bruce256** [apache/rocketmq-dashboard#228]
rocketmq版本：5.3.0
dashboard版本：1.0.1
点击消息详情报错
![image](https://github.com/user-attachments/assets/01501eea-7845-43f3-8edd-6f963222126e)

**Comment by String-hks** [comment]
dashboard版本要升级

**Comment by adminpass** [comment]
> dashboard版本要升级

人员优化，哪还有人去维护升级

![image](https://github.com/user-attachments/assets/14c9dddf-16b3-48fb-9214-937baf97b9a1)

**Comment by bruce256** [comment]
git pull一下最新的代码，重新打包部署，新提交的代码已经解决这个问题了

**Comment by bruce256** [comment]
git pull一下最新的代码，重新打包部署，新提交的代码已经解决这个问题了
