### ISSUE TITLE
Consider whether to add query message by topic and tags

### ISSUE THREAD

**Issue by joewee** [apache/rocketmq-dashboard#24]
Consider whether to add a method that  query message by topic and tags in message query module.

**FEATURE REQUEST**

Consider whether to add a method that  query message by topic and tags in message query module.

**Comment by StyleTang** [comment]
Thanks for your request but we may not add this feature.
Message tags is designed for message filter [Message filtering](https://partners-intl.aliyun.com/help/doc-detail/29543.htm)
If you want to query message by index, you should use `key` but not `tag` (a message can contains multiple keys)
```java
Message msg = new Message("TopicTest",
    "TagA",
    "Hello world".getBytes(RemotingHelper.DEFAULT_CHARSET));
msg.setKeys(Arrays.asList("key1","key2"));   // you by query by both key1 and key2
SendResult sendResult = producer.send(msg);```

Hope this solved your problem.
