### ISSUE TITLE
maven打包报错

### ISSUE THREAD

**Issue by resuper** [apache/rocketmq-dashboard#47]
[INFO] Installed Yarn locally.
[INFO]
[INFO] --- frontend-maven-plugin:1.11.3:yarn (yarn install) @ rocketmq-dashboard ---
[INFO] Running 'yarn install' in F:\github-demos\rocketmq-dashboard\frontend
[INFO] 拒绝访问。
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.843 s
[INFO] Finished at: 2021-11-20T22:38:17+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.3:yarn (yarn install) on project rocketmq-dashboard: Failed to run task: 'yarn install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by StyleTang** [comment]
It seems you executed `maven install` but failed, could you provide your command? It can help us to troubleshoot.
It would be better if you could provide your `node` and `yarn` version.

```
node -v
yarn -v
```

**Comment by vongosling** [comment]
IMO, you should focus on why [INFO] 拒绝访问?

**Comment by chaoxcc** [comment]
你好 我也遇到相同的问题 是怎么解决的呢~
[错误] 无法在项目 rocketmq-dashboard 上执行目标 com.github.eirslett:frontend-maven-plugin:1.11.3:yarn (yarn install)：无法运行任务：“yarn install”失败。org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
yurn 版本   1.22.18

**Comment by bolitao** [comment]
我也出现了这个问题。

排查发现是编译时自动下载 `~/.m2/repository/com/github/eirslett/node/16.2.0` 被手动中断了，导致下载的二进制文件损坏。

解决办法：

- 方法一：你可以手动删掉 `~/.m2/repository/com/github/eirslett/node/16.2.0` 目录，重新运行 `mvn` 编译命令，让其自动重新下载

- 方法二：你可以删掉 `/path/to/node/16.2.0` 目录中的二进制文件 `node-16.2.0-win-x64.exe`，然后通过这个链接重新下载该文件：[node.exe](https://nodejs.org/dist/v16.2.0/win-x64/node.exe)，移动至 `/path/to/node/16.2.0` 并重命名为 `node-16.2.0-win-x64.exe`
  >（我所使用的系统是 Windows，按自己所使用的系统自行重命名）

---

另附一些帮助解决问题的实用文档：

- [Node v16.2.0 (Current) | Node.js](https://nodejs.org/es/blog/release/v16.2.0/)
- [Maven – Guide to using proxies](https://maven.apache.org/guides/mini/guide-proxies.html)
