### ISSUE TITLE
Normal User login after to tips:no permission

### ISSUE THREAD

**Issue by night2049** [apache/rocketmq-dashboard#50]
runtime: docker

run shell:
  rocketmqdashboard:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    container_name: rmq-dashboard
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    links:
      - rmqnameserver
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnameserver:9876
      - "rocketmq.config.loginRequired=true"
      - "rocketmq.config.dataPath=/tmp/rocketmq-console/data"
    volumes:
      - ./env/rmq.properties:/tmp/rocketmq-console/data/users.properties
      - ./env/role-permission.yml:/tmp/rocketmq-console/data/role-permission.yml
    ports:
      - "9875:9875"

**BUG REPORT**
users.properties file add Normal User
web login this Normal User,tips no permission

![image](https://user-images.githubusercontent.com/69810127/145555755-6b68d050-f856-42e3-89c1-5d8a7608d550.png)

**Comment by StyleTang** [comment]
Normal users can only access URIs in the config  `rolePerms.ordinary`.
Could you provide more information for troubleshooting, for example, which URI has no permission?

**Comment by StyleTang** [comment]
After investigating, I found some of the read URIs is not default in the `rolePerms.ordinary` config, it is not a functionality Bug but it really makes user confused. I will create a new PR to improve it.

Thanks for your issue.

**Comment by StyleTang** [comment]
PR has been submitted.
If it is urgent for you, the workaround is to modify the `role-permission.yml` yourself.

**Comment by night2049** [comment]
> PR has been submitted. If it is urgent for you, the workaround is to modify the yourself.`role-permission.yml`

thank you
