### ISSUE TITLE
Make dashboard be enabled to support multiple namesrvs

### ISSUE THREAD

**Issue by cserwen** [apache/rocketmq-dashboard#58]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
- Users can select namesrv from list, just like this:
![image](https://user-images.githubusercontent.com/46882838/148016195-b398c6e2-9634-473e-9c8b-56f9741c5041.png)

2. Provide any additional detail on your proposed use case for this feature.
- Usually, we may deploy many clusters, but we cannot remember so many and complex namesrvs. If we can choose, then it will be very easy to switch between different clusters.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
- nice-to-have

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

**Comment by zhangjidi2016** [comment]
Does it support modification if I want to connect to another RocketMQ cluster that is not in the drop down option originally defined.

**Comment by cserwen** [comment]
> Does it support modification if I want to connect to another RocketMQ cluster that is not in the drop down option originally defined.

It cannot be modified now. But this should be easier to implement, just add an additional interface.😁

**Comment by zhangjidi2016** [comment]
> > Does it support modification if I want to connect to another RocketMQ cluster that is not in the drop down option originally defined.
> 
> It cannot be modified now. But this should be easier to implement, just add an additional interface.😁

The front page can use an editable select element for more flexibility in managing multiple clusters

**Comment by cserwen** [comment]
> > > Does it support modification if I want to connect to another RocketMQ cluster that is not in the drop down option originally defined.
> > 
> > 
> > It cannot be modified now. But this should be easier to implement, just add an additional interface.grin
> 
> The front page can use an editable select element for more flexibility in managing multiple clusters

Not very good at front-end components, how about this：
![image](https://user-images.githubusercontent.com/46882838/148028860-d69b5798-a606-4da8-9be9-768a47e06f7b.png)

**Comment by Git-Yang** [comment]
Merged
