### ISSUE TITLE
控制台修改能否支持多台rocketMQ 集群的查询

### ISSUE THREAD

**Issue by clverhack** [apache/rocketmq-dashboard#67]
如题：我们有多套测试环境，每套测试环境有一个rocketmq 的环境。需要console 去使用。但是每套环境需要单独安装dashboard.
之前试过修改 dashboard的修改namesrv不太好使。

**Comment by cserwen** [comment]
https://github.com/apache/rocketmq-dashboard/issues/58  It is supported to configure multiple namesrvs
