### ISSUE TITLE
Does the dashboard need to provide a visual way to configure acl?

### ISSUE THREAD

**Issue by xxd763795151** [apache/rocketmq-dashboard#70]
**FEATURE REQUEST**
Hello, 
In the year before, I developed a feature that can support config acl int the console for my team, such as following: 
![image](https://user-images.githubusercontent.com/19887530/151118881-78dd441f-e095-475e-8d87-0c618e7c0374.png)
![image](https://user-images.githubusercontent.com/19887530/151118924-f2443f27-67d0-40d8-bf57-0615eb334bb9.png)

Just now，I migrate these code to the dashboard in my local.

I would like to ask this feature is helpful to the community? If it is helpful , can I commit a pr, otherwise I need not going to do that.

**Comment by StyleTang** [comment]
Yes, it is helpful.
You can submit a pull request, and the community will review it.
Thanks.
