### ISSUE TITLE
Failed to query message by Topic

### ISSUE THREAD

**Issue by 6U-U9** [apache/rocketmq-dashboard#79]
I ran the rocketMQ-example quickstart and sent some messages to the broker of http://rocketmq.apacher.cn/.
After I sent the messages, I was able to check my messages by message ID，but not by my topic.
And when I check messages by topic, it returns an error "Can not find Message Queue for this Topic".

My topic names "**2101210386-test-Topic**", 
and one message ID is "**7F0000013E8C1F89AB83371FDA2B0005**" .

按照MsgID可以查询到消息，但是按Topic查询会报错Can not find Message Queue for this Topic
![image](https://user-images.githubusercontent.com/53718342/157841752-8a654ff4-24e8-4e96-8bad-ed0540b76202.png)
![image](https://user-images.githubusercontent.com/53718342/157841770-33b636bc-8992-4e43-bc9d-566ff4bd125b.png)

**Comment by StyleTang** [comment]
Could  you provide more information for troubleshooting? e.g. the version of `RocketMQ Name Server` / `Broker` / `Dashboard`, the configuration you use.

`Query by message id` and `query by message topic` use different methods.

`Query by message id` : parse the message id into `broker address` and `physical offset`, then retrieve message directly.
`Query by message topic`: retrieve router info (message queue) by topic form the name server then pull message from broker.


According to my preliminary judgment, if seems the query name server router info request has problem, not sure whether your nameserver configuration is correct or not, maybe you have to check how you create your topic too.
```java
TopicRouteData topicRouteData = this.mQClientFactory.getMQClientAPIImpl().getTopicRouteInfoFromNameServer(topic, timeoutMillis);
```

**Comment by 6U-U9** [comment]
It turns out that I have wrongly set the topic permission.
Thanks for your reply.
