### ISSUE TITLE
Error in different web brower

### ISSUE THREAD

**Issue by jeasonlyo** [apache/rocketmq-dashboard#80]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by jeasonlyo** [comment]
![image](https://user-images.githubusercontent.com/37092708/160354079-03f06fa6-106a-412a-bca1-566643d12ffa.png)
在linux虚拟机的主机能够正常访问，另外一台机器不行。
![image](https://user-images.githubusercontent.com/37092708/160354759-f3ef32f9-49b5-4d89-9113-d1138b385cdf.png)

**Comment by lixianmin** [comment]
这个在chrome中会打不开, 产生前面@[jeasonlyo](https://github.com/jeasonlyo) 截图的样子, 但是在safari中是可以打开的

**Comment by StyleTang** [comment]
Could you provide the 
* OS version ( such as Windows 10 / CentOS 7.2 xxx / MacOs Big Sur)
* Browser and version (such as Chrome 100.0.4896.88 (Official Build) (x86_64))

Not sure how to reproduce it, it is hard for us to troubleshoot.

**Comment by luyaotang** [comment]
同样的问题。现在修复了没？
