### ISSUE TITLE
使用控制台创建主题的时候，指定了cluster下某一个broker集群，topic也会被加到其它的broker集群下

### ISSUE THREAD

**Issue by dujingsong** [apache/rocketmq-dashboard#84]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

![image](https://user-images.githubusercontent.com/32673188/162400188-4982bd10-638f-4ad1-9cbf-b5f4fc927464.png)

- What did you expect to see?

topic加入到cluster（RaftCluster）下指定broker集群（RaftNode01）中

- What did you see instead?
topic加入到cluster（RaftCluster）下所有broker集群（RaftNode01与RaftNode01）中

2. Please tell us about your environment:

使用master分支

4. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

![image](https://user-images.githubusercontent.com/32673188/162401074-29c0c757-7d4e-4437-a07e-11377d6e297d.png)

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

5. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by zhangjidi2016** [comment]
创建topic时如果同时选择集群名和brokerName，默认会在该集群名下的所有broker中创建topic。如果只想在某个broker中创建topic，只需选择具体的broker，上面的集群名不要选。

**Comment by dujingsong** [comment]
好的 感谢

**Comment by Liguanqin** [comment]
> 创建topic时如果同时选择集群名和brokerName，默认会在该集群名下的所有broker中创建topic。如果只想在某个broker中创建topic，只需选择具体的broker，上面的集群名不要选。

“新增/更新”主体的时候，broker_name列表会把从节点也展示，是不是这个原因导致了就算只采用clusterName的方式去创建主体也会报错：Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: Can't modify topic or subscription group from slave broker, please execute it from master broker.

![image](https://github.com/apache/rocketmq-dashboard/assets/12002367/b2312abc-5605-441a-a5b7-53ce0cab34f0)

![image](https://github.com/apache/rocketmq-dashboard/assets/12002367/9d338d6c-2cad-4421-b129-00a7010e0c27)
