### ISSUE TITLE
manifest for docker.io/apacherocketmq/rocketmq-console:latest not found

### ISSUE THREAD

**Issue by fwhezfwhez** [apache/rocketmq-dashboard#9]
docker pull apacherocketmq/rocketmq-console
Using default tag: latest
Trying to pull repository docker.io/apacherocketmq/rocketmq-console ...
manifest for docker.io/apacherocketmq/rocketmq-console:latest not found

daemon.json
{
 "registry-mirrors": ["https://registry.docker-cn.com"]
}

Which mirror provides acessible image

**Comment by StyleTang** [comment]
Could you try
```
docker pull apacherocketmq/rocketmq-console:2.0.0
```
We can find the tags [here](https://hub.docker.com/r/apacherocketmq/rocketmq-console/tags?page=1&ordering=last_updated)

**Comment by fwhezfwhez** [comment]
3q done

**Comment by vongosling** [comment]
@francisoliverlee
