### ISSUE TITLE
Cluster cannot register more than one

### ISSUE THREAD

**Issue by changefate** [apache/rocketmq-dashboard#90]
1.I configure two rocketmq
![image](https://user-images.githubusercontent.com/8042946/167771456-b30bef9c-af21-4708-b1fc-b5d0a48729ca.png)
2.The console only shows one
![image](https://user-images.githubusercontent.com/8042946/167771670-68c16fd8-cc8e-40db-af8b-eb3f7b483fd1.png)
3.I found the source code according to the configuration and found that it only takes the first line
![image](https://user-images.githubusercontent.com/8042946/167771864-258ff19d-da7a-4b4e-9361-60b59a2f24ff.png)
4.Excuse me, where did I match it wrong, or is it a design problem?Looking forward to reply, thanks

**Comment by cserwen** [comment]
It will choose the first namesrv as the default value, you can change it to other namesrv on the OPS page.

**Comment by changefate** [comment]
Ok,It means that in a cluster, only one node can be displayed in the dashboard. It is recommended to display all nodes for easy monitoring

**Comment by changefate** [comment]
Knowing your design, you can switch it in the operation and maintenance menu
