### ISSUE TITLE
dleger集群创建topic指定单一broker不生效

### ISSUE THREAD

**Issue by mashuangwei** [apache/rocketmq-dashboard#96]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
我的集群是dleger模式，集群是两主四从,使用控制台创建topic，创建topic页面broker选择时只选择其中一个，然后提交成功后，发现topic配置详情页面是配置了两个broker。

- What did you expect to see?
![image](https://user-images.githubusercontent.com/7100779/172982004-0eed0ba7-6390-42f2-a98f-9136dbae061c.png)

![image](https://user-images.githubusercontent.com/7100779/172982111-d77fc395-db75-43b8-b9e5-8b3437d4ba05.png)

- What did you see instead?

2. Please tell us about your environment:
rocketmq-dashboard 1.0.1 版本、mq4.9.3
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by zhangjidi2016** [comment]
If you only want to create on a broker, do not select the clusterName above, just select the broker you want to create.
